//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 11:19:50 PM CEST 
//


package com.tibco.exchange.tibreview.model.rules;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cond complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cond">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="if" type="{exchange.tibco.com/tibreview}if"/>
 *         &lt;element name="elseif" type="{exchange.tibco.com/tibreview}elseif" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="else" type="{exchange.tibco.com/tibreview}else" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cond", propOrder = {
    "_if",
    "elseif",
    "_else"
})
public class Cond {

    @XmlElement(name = "if", required = true)
    protected If _if;
    protected List<Elseif> elseif;
    @XmlElement(name = "else")
    protected Else _else;

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link If }
     *     
     */
    public If getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link If }
     *     
     */
    public void setIf(If value) {
        this._if = value;
    }

    /**
     * Gets the value of the elseif property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elseif property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElseif().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Elseif }
     * 
     * 
     */
    public List<Elseif> getElseif() {
        if (elseif == null) {
            elseif = new ArrayList<Elseif>();
        }
        return this.elseif;
    }

    /**
     * Gets the value of the else property.
     * 
     * @return
     *     possible object is
     *     {@link Else }
     *     
     */
    public Else getElse() {
        return _else;
    }

    /**
     * Sets the value of the else property.
     * 
     * @param value
     *     allowed object is
     *     {@link Else }
     *     
     */
    public void setElse(Else value) {
        this._else = value;
    }

}
