//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 11:19:50 PM CEST 
//


package com.tibco.exchange.tibreview.model.rules;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for elseif complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="elseif">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="xpath" type="{exchange.tibco.com/tibreview}xpath"/>
 *           &lt;element name="cond" type="{exchange.tibco.com/tibreview}cond"/>
 *           &lt;element name="not" type="{exchange.tibco.com/tibreview}not"/>
 *           &lt;element name="java" type="{exchange.tibco.com/tibreview}java"/>
 *         &lt;/choice>
 *         &lt;element name="then" type="{exchange.tibco.com/tibreview}impl"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elseif", propOrder = {
    "xpath",
    "cond",
    "not",
    "java",
    "then"
})
public class Elseif {

    protected Xpath xpath;
    protected Cond cond;
    protected Not not;
    protected Java java;
    @XmlElement(required = true)
    protected Impl then;

    /**
     * Gets the value of the xpath property.
     * 
     * @return
     *     possible object is
     *     {@link Xpath }
     *     
     */
    public Xpath getXpath() {
        return xpath;
    }

    /**
     * Sets the value of the xpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xpath }
     *     
     */
    public void setXpath(Xpath value) {
        this.xpath = value;
    }

    /**
     * Gets the value of the cond property.
     * 
     * @return
     *     possible object is
     *     {@link Cond }
     *     
     */
    public Cond getCond() {
        return cond;
    }

    /**
     * Sets the value of the cond property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cond }
     *     
     */
    public void setCond(Cond value) {
        this.cond = value;
    }

    /**
     * Gets the value of the not property.
     * 
     * @return
     *     possible object is
     *     {@link Not }
     *     
     */
    public Not getNot() {
        return not;
    }

    /**
     * Sets the value of the not property.
     * 
     * @param value
     *     allowed object is
     *     {@link Not }
     *     
     */
    public void setNot(Not value) {
        this.not = value;
    }

    /**
     * Gets the value of the java property.
     * 
     * @return
     *     possible object is
     *     {@link Java }
     *     
     */
    public Java getJava() {
        return java;
    }

    /**
     * Sets the value of the java property.
     * 
     * @param value
     *     allowed object is
     *     {@link Java }
     *     
     */
    public void setJava(Java value) {
        this.java = value;
    }

    /**
     * Gets the value of the then property.
     * 
     * @return
     *     possible object is
     *     {@link Impl }
     *     
     */
    public Impl getThen() {
        return then;
    }

    /**
     * Sets the value of the then property.
     * 
     * @param value
     *     allowed object is
     *     {@link Impl }
     *     
     */
    public void setThen(Impl value) {
        this.then = value;
    }

}
